# Generated by Django 2.0.7 on 2018-08-16 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_n', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_borrower_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CleanedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='ExtractedDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_n', models.IntegerField(db_index=True)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(default='IDLE', max_length=50, protected=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('n_extracted_data_points', models.IntegerField(default=-1)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='FileSchemaJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(default='IDLE', max_length=50, protected=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('n_sheets', models.IntegerField(default=-1)),
                ('n_columns', models.IntegerField(default=-1)),
                ('cleaned_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.CleanedFile')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_n', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_borrower_id', models.CharField(db_index=True, max_length=255)),
                ('external_loan_id', models.CharField(db_index=True, max_length=255)),
                ('external_portfolio_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gbv', models.FloatField()),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('default_date', models.DateField(blank=True, null=True)),
                ('principal', models.FloatField()),
                ('loan_class', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('rec_6', models.FloatField(blank=True, null=True)),
                ('rec_12', models.FloatField(blank=True, null=True)),
                ('rec_18', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_schema_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.FileSchemaJob')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='MappingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_params', models.TextField(blank=True, help_text='For dates we use datetime.strptime.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapped_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Mapping')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_n', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_loan_id', models.CharField(db_index=True, max_length=255)),
                ('pay_date', models.DateField()),
                ('amount', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PopulateJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(default='IDLE', max_length=50, protected=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('n_borrowers', models.IntegerField(default=-1)),
                ('n_loans', models.IntegerField(default=-1)),
                ('n_payments', models.IntegerField(default=-1)),
                ('extract_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.ExtractJob')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=255, unique=True)),
                ('state', models.CharField(choices=[('UPLOADED', 'UPLOADED'), ('PROCESSING', 'PROCESSING'), ('DONE', 'DONE')], default='UPLOADED', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SourceColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_sheet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('source_sheet', 'index'),
            },
        ),
        migrations.CreateModel(
            name='SourceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_schema_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.FileSchemaJob')),
            ],
        ),
        migrations.CreateModel(
            name='TargetField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text="Model's attribute, not the column name.", max_length=255)),
            ],
            options={
                'ordering': ('target_model_name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TargetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddField(
            model_name='targetfield',
            name='target_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.TargetModel'),
        ),
        migrations.AddField(
            model_name='sourcecolumn',
            name='source_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.SourceSheet'),
        ),
        migrations.AddField(
            model_name='payment',
            name='populate_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.PopulateJob'),
        ),
        migrations.AddField(
            model_name='mappingrule',
            name='source_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.SourceColumn'),
        ),
        migrations.AddField(
            model_name='mappingrule',
            name='target_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.TargetField'),
        ),
        migrations.AddField(
            model_name='loan',
            name='populate_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.PopulateJob'),
        ),
        migrations.AddField(
            model_name='extractjob',
            name='mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Mapping'),
        ),
        migrations.AddField(
            model_name='extractjob',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extracteddatapoint',
            name='extract_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.ExtractJob'),
        ),
        migrations.AddField(
            model_name='extracteddatapoint',
            name='mapping_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.MappingRule'),
        ),
        migrations.AddField(
            model_name='cleanedfile',
            name='uploaded_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.UploadedFile'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='populate_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.PopulateJob'),
        ),
        migrations.AlterUniqueTogether(
            name='extracteddatapoint',
            unique_together={('extract_job', 'mapping_rule', 'row_n')},
        ),
        migrations.AlterUniqueTogether(
            name='borrower',
            unique_together={('populate_job', 'external_borrower_id')},
        ),
    ]
