# Generated by Django 2.0.7 on 2018-12-13 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0003_auto_20181010_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(default='IDLE', max_length=50, protected=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('n_default_cases', models.IntegerField(default=-1)),
                ('n_paid_cases', models.IntegerField(default=-1)),
                ('mean_recovery_rate_6', models.FloatField(default=0)),
                ('mean_recovery_rate_12', models.FloatField(default=0)),
                ('mean_recovery_rate_18', models.FloatField(default=0)),
                ('populate_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.PopulateJob')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
